services:
  # Ollama: LLM server
  ollama:
    image: ollama/ollama
    # this will create the .ollama folder
    volumes:
      - ollama_data:/root/.ollama

    # uncommented this becuase i want to choose what model
    # command: >
    #   sh -c "ollama pull llama3 && ollama serve"

    # to pull a model
    # docker exec -it rag_about_me-ollama-1 bash    
    # ollama list
    # ollama pull (model)


    ports:
      - "11434:11434"

  # Backend: FastAPI + RAG
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    depends_on:
      - ollama
    volumes:
      - ./data:/app/data           # host data is editable
      - chroma_data:/app/chroma_db # persistent vectors
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434/api/generate
      # two models are pull in .ollama volume (gemma3n-4b-it-4bit and gemma3 1b-it-qat)
      - OLLAMA_MODEL=gemma3:1b-it-qat

  # Frontend: Streamli
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    depends_on:
      - backend
    ports:
      - "8501:8501"
    environment:
      - BACKEND_URL=http://backend:8000/chat

volumes:
  ollama_data:
  chroma_data:
